### ISSUE TITLE
DecentHolograms - Sometimes the holograms disappear.

### ISSUE THREAD

**Issue by Fredh1000** [TitaniumMC/Titanium#102]
I don't know why, but if a chunk with a hologram is unloaded and then realoaded, there is a chance that the hologram will no longer be seen (as a plugin for holograms I use decent holograms). This does not happen with other forks and I don't understand what it is due to.

**Comment by P3ridot** [comment]
I don't know what is the reason, but are you using async entity tracker?

**Comment by Fredh1000** [comment]
Yes, i use async entity tracker.

**Comment by P3ridot** [comment]
So when you disable it everything works fine?

**Comment by Fredh1000** [comment]
Yes, i disable the Async Entity Tracker and this problem no longer occur.

**Comment by Fredh1000** [comment]
It appears not to be a Titanium-related problem. I have tested several times and it always happens anyway.

**Comment by Fredh1000** [comment]
I close this issue.
