### ISSUE TITLE
Book editing is not working

### ISSUE THREAD

**Issue by jonesdevelopment** [TitaniumMC/Titanium#103]
Whenever you try to edit a book and quill, it will instantly kick you for 'Invalid book data!' and not save your book page(s).

Titanium version: 0.9.4
Minecraft version: 1.8.9
Edit: The client used is not the problem. This also happens on vanilla clients.

![image](https://user-images.githubusercontent.com/73846784/199827339-f58e9db1-c5df-478f-97e3-9cf5f6b3a685.png)
![image](https://user-images.githubusercontent.com/73846784/199827377-408235f0-d7fb-46fc-abf0-8e22583896a6.png)

Signing a book is not a problem, only editing and then clicking on 'Done' will throw [an exception](https://user-images.githubusercontent.com/73846784/199827099-d7687ff3-2529-4177-b249-56d0fc3ff9ee.png).

![image](https://user-images.githubusercontent.com/73846784/199827271-b95ab5f7-fc06-40a2-96d2-14be531eb18d.png)

Exception:
![image](https://user-images.githubusercontent.com/73846784/199827099-d7687ff3-2529-4177-b249-56d0fc3ff9ee.png)

The fix is somewhere in the processing of the book information. This could be fatal for survival/building servers.

**Comment by P3ridot** [comment]
I can't really reproduce that and everything works fine 🤔 Could you pass your plugin list? Or maybe try latest `dev` build?

**Comment by jonesdevelopment** [comment]
I don't have any plugins on that server. I created a new folder to test it. There a no special settings or configuration changes.
![image](https://user-images.githubusercontent.com/73846784/200129601-1a8db300-f99b-4341-aa17-203a8d949db8.png)

It still happens on the latest dev version:
![image](https://user-images.githubusercontent.com/73846784/200129641-030fa923-403f-4fae-a1fc-3600a061fbc3.png)

You can add me on Discord if you want to directly contact me for testing: Jones#3279

**Comment by P3ridot** [comment]
Okay, I reset everything and now it's appearing.... So I'm gonna try to fix this

**Comment by P3ridot** [comment]
> Okay, I reset everything and now it's appearing.... So I'm gonna try to fix this

Okay, I checked and it's something with book.max-pages when value is set to '-1'. Changing this value to something else like '50' or something resolves this issue....

**Comment by P3ridot** [comment]
@jonesdevelopment can you test latest dev build? There everything should works

**Comment by jonesdevelopment** [comment]
> @jonesdevelopment can you test latest dev build? There everything should works

It is working now. Thank you very much.
