### ISSUE TITLE
KnockBack and fireworks of crackshot plugin projectiles are broken

### ISSUE THREAD

**Issue by Fredh1000** [TitaniumMC/Titanium#105]
I don't know how to explain, so I made a video:
Link: https://www.youtube.com/watch?v=OK1lSWtl_c8

**Comment by P3ridot** [comment]
Could you test latest `dev` build? Just remember to delete `knockback.yml` before testing (I used wrong values in some places to calculate knockback)

**Comment by Fredh1000** [comment]
Unfortunately nothing has changed.

**Comment by Fredh1000** [comment]
Ah, I forgot to mention. If I have "fix-east-west-cannoning" the effect of this "broken knockback" is amplified by about double if I shoot the mob from west to east.

**Comment by P3ridot** [comment]
Could again try latest `dev` build? At least `fix-east-west-cannoning` - now effect of "broken knockback" shouldn't be amplified

**Comment by Fredh1000** [comment]
Now the effect is no longer amplified by fix-east-west-cannoning, but it's still there.

**Comment by Fredh1000** [comment]
Were you able to find a solution for these two problems? The problem inherent to the firework that does not explode was also present on WindSpigot if you kept async-entitytracker on false (the wind async entity tracker gave problems and therefore had to be deactivated, but if you deactivated it gave this problem).

**Comment by Fredh1000** [comment]
As for the knockback issue I have no idea, I've never seen such a thing. In new versions not vertical knockback, but such a strange knockback I have never seen.

**Comment by P3ridot** [comment]
I unfortunately can't find issue for now. It seems really complicated (especially if it's correlated to entity tracker). I'll have to do lots of debugging etc. I'll try to do is ASAP, but I'm currently really busy so I don't have much time

**Comment by Fredh1000** [comment]
I tried to test multiple times and none of the options affect the knockback, not even taco's tnt movement optimize.

**Comment by P3ridot** [comment]
Fixed in `dev` branch. Just remember to delete `knockback.yml` or set `horizontal-min` & `horizontal-max` to high values (like -100 and 100)
