### ISSUE TITLE
ConcurrentModificationException in AsyncEntityTracker

### ISSUE THREAD

**Issue by Fredh1000** [TitaniumMC/Titanium#120]
The server goes to 0 tps when I move to a particular area of ​​the world where I spawned a villager and gave it resistance 255.
The error appear in console: 
![Screenshot (295)](https://user-images.githubusercontent.com/82319919/206899771-969193e4-9325-4137-ab19-b48c91d03c4c.png)

**Comment by Fredh1000** [comment]
The error is not always reported in the console. Sometimes the server stops for 4 minutes, kicks you off the server and then comes back up without errors.

**Comment by P3ridot** [comment]
Please try latest `dev` build from jenkins

**Comment by Fredh1000** [comment]
It didn't resolve the problem:
[error.txt](https://github.com/TitaniumMC/Titanium/files/10251342/error.txt)

**Comment by P3ridot** [comment]
Do you have any more server crashes logs? It would be really helpful...

**Comment by Fredh1000** [comment]
I think I understand where the problem is coming from. I spawned entities, then changed the remove-rate of the entity tracker and restarted the server, everything was fine until I got close to that entity.

**Comment by P3ridot** [comment]
Oh, so which values did you change? And to what values...

**Comment by Fredh1000** [comment]
From what I remember animals and monsters 10 to 5 in the async entity tracker.

**Comment by P3ridot** [comment]
And if you change it back to 10 it resolve the issue?

**Comment by Fredh1000** [comment]
I made it back to 10 but the problem is still occur.

**Comment by P3ridot** [comment]
Could you again test latest `dev` branch? Build 106

**Comment by P3ridot** [comment]
I think it's fixed - if not I will reopen this PR...
