### ISSUE TITLE
Backport PlayerProfile API from Paper 1.12+

### ISSUE THREAD

**Issue by nwseOOO** [TitaniumMC/Titanium#123]
Why? So we can better deal with profiles (nms GameProfile).
https://jd.papermc.io/paper/1.12/com/destroystokyo/paper/profile/PlayerProfile.html

**Comment by P3ridot** [comment]
Titanium actually has `PlayerProfile` API - https://repo.titanvale.net/javadoc/snapshots/net/titanvale/titanium-api/1.8.8-R0.1-SNAPSHOT

**Comment by nwseOOO** [comment]
oh I thought it doesn't! thanks!
