### ISSUE TITLE
ProtocolLib not working

### ISSUE THREAD

**Issue by Regomy** [TitaniumMC/Titanium#131]
https://paste.md-5.net/ciqufoloyu.cpp

**Comment by c0dingnoobi** [comment]
update to latest protocollib and see if issue still happens

**Comment by c0dingnoobi** [comment]
>  I use a plugin that I can not remove, and it does not work with the new ones.

which plugin is that? just curious

**Comment by Regomy** [comment]
> > I use a plugin that I can not remove, and it does not work with the new ones.
> 
> which plugin is that? just curious

AAC)

**Comment by c0dingnoobi** [comment]
aac3 is pretty much outdated. i would not recommend something like that as an anticheat solution. 
also since ur using aac3 instead of aac5 i am assuming that this one is a cracked version. 
another reason why to drop of that plugin. 
throughout ur role as server admin you will realize that protocollib on higher versions is needed for multitple plugins which might be necessary for you. 
consider updating your anticheat. having aac3 is basically like having not an anticheat at all (aac5 even has been released, thats TWO whole new versions)

**Comment by Regomy** [comment]
> aac3 is pretty much outdated. i would not recommend something like that as an anticheat solution. also since ur using aac3 instead of aac5 i am assuming that this one is a cracked version. another reason why to drop of that plugin. throughout ur role as server admin you will realize that protocollib on higher versions is needed for multitple plugins which might be necessary for you. consider updating your anticheat. having aac3 is basically like having not an anticheat at all (aac5 even has been released, thats TWO whole new versions compared to your current)

I do not forbid cheats, that's why I use 1.8. I have another 1 bug, but I can not check it because of the protocol, I would appreciate if you fix this nonsense with packets.

**Comment by c0dingnoobi** [comment]
> I do not forbid cheats 

one more reason to stop using aac3 ig xd

> I would appreciate if you fix this nonsense with packets

dont get what u exactly meant by that

**Comment by Regomy** [comment]
> > I do not forbid cheats
> 
> one more reason to stop using aac3 ig xd
> 
> > I would appreciate if you fix this nonsense with packets
> 
> dont get what u exactly meant by that

Spam error in the console I attached (https://paste.md-5.net/ciqufoloyu.cpp). There is no such thing on the spigot 1.8.8 kernel. Everything works like a Swiss watch. And about the anti-cheat, well, let's just say, it is not very nice to play on the direct xvh, you need the balance, players can bypass, but they can kick, however, you can write and complete bypass, well, it is up to them. The only downside - optimization, it eats 5% of the CPU.

**Comment by c0dingnoobi** [comment]
im not collaborator of this project, just a normal user like u. 
peridot might take a look at this convo and will decide on his own if he will try to fix this or not. 
imo as issue creator u should try to run protocollib (without aac3) and see if the issue persists to make sure protocollib v4.6 is the cause.

**Comment by Regomy** [comment]
А... I somehow didn't even pay attention to your nickname. Okay, I'll try a newer version.

**Comment by Regomy** [comment]
> If newer ProtocolLib works properly I unfortunately would close this issue... I want to make Titanium as much compatible with Spigot/Paper 1.8.8, but sometimes it's not possible. Maybe in future I would write dependency loader like these ImanitySpigot has, but now I don't have much time to do that

It's sad, but maybe it's for the best. In any case, until you make support for the old protocol, I will be forced to leave your kernel. Yes, the new version works fine.
