### ISSUE TITLE
TPS problem

### ISSUE THREAD

**Issue by Regomy** [TitaniumMC/Titanium#132]
https://spark.lucko.me/3wP5Jh3QFW

**Comment by c0dingnoobi** [comment]
its normal to show the tps off for boot time since it reaches even 30 tps when booting up the system (dont ask me why also discovered) 
your process wasnt running long enough to average to 20 tps

**Comment by P3ridot** [comment]
Like @c0dingnoobi mentioned you probably runned server for too short
