### ISSUE TITLE
Add WaterSourceFormEvent

### ISSUE THREAD

**Issue by c0dingnoobi** [TitaniumMC/Titanium#134]
https://github.com/Electroid/SportPaper/commit/04c34e36607789e9d8c63497d84d236a00e8a592#diff-701c1d3ee91cf5f11d547f9d3c63b66d0feca235d5db4e1adac8b24bd5eefd91
patch by a fork of sportpaper (https://github.com/StratusNetwork/SportPaper), dk if paper has this one too

**Comment by P3ridot** [comment]
Soon it should be available when jenkins will finish building
