### ISSUE TITLE
Add PlayerArmorChangeEvent

### ISSUE THREAD

**Issue by c0dingnoobi** [TitaniumMC/Titanium#136]
https://jd.papermc.io/paper/1.16/com/destroystokyo/paper/event/player/PlayerArmorChangeEvent.html

**Comment by P3ridot** [comment]
I recently added EquipmentSetEvent (3b5de66a5d3ded4a0f1522f16adebb88aadff6f6), but I think I could also add this PlayerAmorChangeEvent

**Comment by c0dingnoobi** [comment]
Ah, mb havent even looked up if something similar exists. Im gonna stick with EquipmentSetEvent for now. thx

**Comment by P3ridot** [comment]
I added this event in latest `dev` build but you probably still should use EquipmentSetEvent
