### ISSUE TITLE
Parallel Chunk Generation

### ISSUE THREAD

**Issue by P3ridot** [TitaniumMC/Titanium#45]
https://github.com/TitanVale/Titanium/pull/12

**Comment by P3ridot** [comment]
If we would like to rewrite Minecraft generator we would still have to synchronize it in some point since generation is neighbour-aware. Maybe first and most simple approach would be to not compleatly make generation parallel, but to just move generation off main thread.

**Comment by F1rsi** [comment]
It would be better in my opinion to have a configurable parallel generation of chunks

**Comment by P3ridot** [comment]
I know, having something like that not configurable is terrible idea. Current minecraft generator sometimes produce artifacts, let alone when it would be async.

**Comment by F1rsi** [comment]
What do you mean by generation artifacts?
Broken sids?

**Comment by P3ridot** [comment]
Sometimes chunk generation doesn't work properly and some chunks appear higher etc. It's very rare but it's happened for me 
several times

**Comment by HEROOSTECH** [comment]
Just use paper or forks on 1.13+. 1.8.8 is very old. And you should update. http://howoldisminecraft188.today/

**Comment by P3ridot** [comment]
I know, I'm actually not using 1.8.8 too. I'm just doing this project to see how far I can push that old minecraft version without exploding everything ¯\_(ツ)_/¯

**Comment by LewUwU** [comment]
If you backport the 1.13 chunk system then you can backport the async chunk patch from Paper 1.13.2

**Comment by P3ridot** [comment]
> If you backport the 1.13 chunk system then you can backport the async chunk patch from Paper 1.13.2

It doesn't seem easy since 1.13 chunk system looks very different compared to 1.8.8 chunk system, but maybe it's only impression

**Comment by LewUwU** [comment]
> > If you backport the 1.13 chunk system then you can backport the async chunk patch from Paper 1.13.2
> 
> It doesn't seem easy since 1.13 chunk system looks very different compared to 1.8.8 chunk system, but maybe it's only impression

People already backported that to 1.8.8 a example of that is ImanitySpigot

**Comment by P3ridot** [comment]
So maybe when I will have more time I will try to achieve this

**Comment by P3ridot** [comment]
Currently I'm trying to backport Paper 1.13.2 chunk system, but leaving Paper 1.8.8 Chunk system for compatibility. Currently it's not working very well, but if starts I will create PR and test builds.

**Comment by P3ridot** [comment]
Now avaible in latest `dev` build
