### ISSUE TITLE
TNT doesn't cause block damage

### ISSUE THREAD

**Issue by Fredh1000** [TitaniumMC/Titanium#95]
When tnt explode, it doesn't cause any block damage.

**Comment by P3ridot** [comment]
Are you using dev build or latest release?

**Comment by Fredh1000** [comment]
Latest dev build.

**Comment by P3ridot** [comment]
Okay, I'll check it - maybe I broke something and not tested and this is the reason it's not working

**Comment by P3ridot** [comment]
Weird, I can't reproduce that - for me on latest `dev` build everything works. Maybe some plugin doesn't work like intended?

**Comment by Fredh1000** [comment]
Is fixed in latest dev.
