### ISSUE TITLE
IllegalStateException when using legacy Chunk System

### ISSUE THREAD

**Issue by Fredh1000** [TitaniumMC/Titanium#97]
I have received this error many times and repeatedly after doing a command after I have been afk for 4-5 minutes:
![Screenshot (258)](https://user-images.githubusercontent.com/82319919/198983837-68ae176b-d145-46b1-a034-3da3ddaafc27.png)

**Comment by P3ridot** [comment]
In the latest `dev` builld everything should work - if not let me know

**Comment by Fredh1000** [comment]
Is fixed, thanks!
